<?php

// Hook_init
function oversea_intensive_subject_init() {
	$path = current_path(); // e.g. It return node/1234
	$path = drupal_get_path_alias($path); // e.g. It returns graduate-studies/coursework/planning/overseas-intensive-subjects

	if(preg_match('|^graduate\-studies/coursework/planning/overseas-intensive-subjects(/.*)?|', $path, $matches)) {
		drupal_add_js(drupal_get_path('module', 'oversea_intensive_subject') . '/js/moment.min.js');
		drupal_add_js(drupal_get_path('module', 'oversea_intensive_subject') . '/js/oversea_intensive_subject.js');
  }

}

